#!/usr/bin/env bash
#
# Donkey Kong by Invader
#
# Depicts Donkey Kong from nintendo games. 
#
# Author: rob o'leary

f=3 b=4

for j in f b; do
	for i in {0..7}; do
		printf -v $j$i %b "\e[${!j}${i}m"
	done
done

for i in {0..7}; do
		printf -v g$i %b "\e[9${i}m"
done

bd=$'\e[1m'
rt=$'\e[0m'
iv=$'\e[7m'

cat << EOF

    $g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█      $f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█                      
    $g3█$g3█$f3█$f3█$g3█$g3█$g3█$g3█    $f3█$f3█$f3█$f3█$g3█$g3█$g3█$g3█$g3█$g3█$f3█$f3█$f3█$f3█                    
    $g3█$g3█$g3█$g3█$f3█$f3█$g3█$g3█$f3█$f3█$g3█$g3█$f3█$f3█$g3█$g3█$g7█$g7█$g7█$g7█$g7█$g7█$g3█$g3█$f3█$f3█$g3█$g3█                  
      $g3█$g3█$g3█$g3█$g3█$g3█$f3█$f3█$g3█$g3█$g3█$g3█$g7█$g7█$f0█$f0█$g7█$g7█$f0█$f0█$g7█$g7█$g3█$g3█$g3█$g3█                  
          $f3█$f3█$f3█$f3█$f3█$f3█$g3█$g3█$g3█$g3█$f3█$f3█$f3█$f3█$f3█$f3█$g3█$g3█$g3█$g3█$f3█$f3█$g3█$g3█                
  $g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█  $g3█$g3█$g3█$g3█$f3█$f3█$f3█$f3█$g3█$g3█$g3█$g3█$g3█$g3█$f3█$f3█$f3█$f3█$g3█$g3█$g3█$g3█$f3█$f3█              
  $g3█$g3█$g3█$g3█$f3█$f3█$g3█$g3█  $g3█$g3█$f3█$f3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$f3█$f3█              
  $g3█$g3█$g3█$g3█$g3█$g3█$f3█$f3█$f3█$f3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$f3█$f3█              
      $f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$f3█$f3█                
         $g3█$g3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█                
           $g3█$g3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$g7█$g7█                
         $f3█$f3█$f3█$f3█$f3█$f3█$g3█$g3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█                
       $f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█                  
       $f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█                   
         $f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█                     
  $g3█$g3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█  $f3█$f3█$f3█$f3█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█                       
    $g3█$g3█$f3█$f3█$f3█$f3█$f3█$f3█$f3█      $g7█$g7█$g7█$g7█$g7█$g7█$rt
EOF
