#!/usr/bin/env bash

# Alladin Sane Clyde (Orange) by Invader (2014)
#
# See: https://www.widewalls.ch/artwork/space-invader/aladdin-sane-clyde-orange
#
# Author: rob o'leary

f=3 b=4

for j in f b; do
	for i in {0..7}; do
		printf -v $j$i %b "\e[${!j}${i}m"
	done
done

for i in {0..7}; do
		printf -v g$i %b "\e[9${i}m"
done

bd=$'\e[1m'
rt=$'\e[0m'
iv=$'\e[7m'

cat << EOF

  $g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█
  $g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g3█$g3█$g3█$g3█$g4█$g4█$g4█$g4█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█
  $g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g3█$g3█$g3█$g3█$g3█$g3█$g4█$g4█$g4█$g4█$f1█$f1█$f1█$f1█$f1█$f1█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█
  $g7█$g7█$g7█$g7█$g7█$g7█$g3█$g3█$g3█$g3█$g3█$g3█$g4█$g4█$g4█$g4█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$g7█$g7█$g7█$g7█$g7█$g7█
  $g7█$g7█$g7█$g7█$g3█$g3█$g3█$g3█$g3█$g3█$g4█$g4█$g4█$g4█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$g3█$g3█$g7█$g7█$g7█$g7█
  $g7█$g7█$g7█$g7█$g3█$g3█$g3█$g3█$g7█$g7█$g7█$g7█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$g7█$g7█$g7█$g7█$g3█$g3█$g3█$g3█$g7█$g7█$g7█$g7█
  $g7█$g7█$g7█$g7█$g3█$g3█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$f1█$f1█$f1█$f1█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g3█$g3█$g7█$g7█$g7█$g7█
  $g7█$g7█$g3█$g3█$g4█$g4█$g7█$g7█$g7█$g7█$f4█$f4█$f4█$f4█$f1█$f1█$f1█$f1█$g7█$g7█$g7█$g7█$g4█$g4█$g4█$g4█$g3█$g3█$g3█$g3█$g7█$g7█
  $g7█$g7█$g4█$g4█$g4█$g4█$g7█$g7█$g7█$g7█$f4█$f4█$f4█$f4█$f1█$f1█$f1█$f1█$g7█$g7█$g7█$g7█$g4█$g4█$g4█$g4█$g3█$g3█$g3█$g3█$g7█$g7█
  $g7█$g7█$g4█$g4█$f1█$f1█$f1█$f1█$g7█$g7█$g7█$g7█$f1█$f1█$f1█$f1█$g3█$g3█$g3█$g3█$g7█$g7█$g7█$g7█$g3█$g3█$g3█$g3█$g3█$g3█$g7█$g7█
  $g7█$g7█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g7█$g7█
  $g7█$g7█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g7█$g7█
  $g7█$g7█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$f1█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g7█$g7█
  $g7█$g7█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g4█$g4█$f1█$f1█$f1█$f1█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g3█$g7█$g7█
  $g7█$g7█$g3█$g3█$g3█$g3█$g7█$g7█$g4█$g4█$f1█$f1█$f1█$f1█$g7█$g7█$g7█$g7█$g3█$g3█$g3█$g3█$g3█$g3█$g7█$g7█$g3█$g3█$g3█$g3█$g7█$g7█
  $g7█$g7█$g3█$g3█$g7█$g7█$g7█$g7█$g7█$g7█$f1█$f1█$g3█$g3█$g7█$g7█$g7█$g7█$g3█$g3█$g3█$g3█$g7█$g7█$g7█$g7█$g7█$g7█$g3█$g3█$g7█$g7█
  $g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$g7█$rt
EOF
